[sources.random]
type = "generator"
format = "apache_common"
interval = 1

[sinks.file]
type = "file"
inputs = ["random"]
path = "/tmp/logs/vector-%Y-%m-%d.log"
encoding = { codec = "ndjson", timestamp_format = "rfc3339" }