[sources.file_in]
type = "file"
include = ["/tmp/logs/iot/*.log"]
read_from = "beginning"

[transforms.tag]
type = "remap"
inputs = ["file_in"]
source = '''
.tags.type = "iot"
'''

[sinks.aggregator]
type = "vector"
inputs = ["tag"]
address = "vector_aggregator:9000"
version = "2"
healthcheck = { enabled = true }