[api]
enabled = true
address = "0.0.0.0:8686"

[sources.vector_agents]
type = "vector"
address = "0.0.0.0:9000"
version = "2"

[sources.datadog_agents]
type = "datadog_agent"
address = "0.0.0.0:8080"
store_api_key = false

[sources.fluent_bit_agents]
type = "fluent"
address = "0.0.0.0:24224"

[sources.prometheus_node_exporter]
type = "prometheus_scrape"
endpoints = ["http://node_exporter:9100/metrics"]
scrape_interval_secs = 5

[transforms.add_tags_to_metrics]
type = "remap"
inputs = ["prometheus_node_exporter"]
source = '''
.tags.environment = "production"
'''

[transforms.logs_router]
type = "route"
inputs = ["*_agents"]

[transforms.logs_router.route]
http_logs = '.tag == "http_logs"'
syslog_logs = '.tag == "syslog_logs"'
datadog_agent_logs = '.tag == "datadog_agent_logs"'
fluent_bit_logs = '.tag == "fluent_bit_logs"'

[transforms.parse_and_sanitize_http_logs]
type = "remap"
inputs = ["logs_router.http_logs"]
source = '''
.
'''

# Convert Syslog logs to JSON objects
[transforms.parse_and_sanitize_syslog_logs]
type = "remap"
inputs = ["logs_router.syslog_logs"]
source = '''
.
'''

[transforms.parse_and_sanitize_datadog_agent_logs]
type = "remap"
inputs = ["logs_router.datadog_agent_logs"]
source = '''
.
'''

[transforms.parse_and_sanitize_fluent_bit_logs]
type = "remap"
inputs = ["logs_router.fluent_bit_logs"]
source = '''
.
'''

# Filter out OPTION requests
[transforms.filter_http_logs]
type = "filter"
inputs = ["parse_and_sanitize_http_logs"]
condition = 'true'

# Filter out non-urgent logs
[transforms.filter_syslog_logs]
type = "filter"
inputs = ["parse_and_sanitize_syslog_logs"]
condition = 'true'

[sinks.datadog_logs]
type = "datadog_logs"
inputs = ["filter_*", "parse_and_sanitize_datadog_agent_logs", "parse_and_sanitize_fluent_bit_logs"]
default_api_key = "${DD_API_KEY}"
compression = "gzip"

[sinks.datadog_metrics]
type = "datadog_metrics"
inputs = ["add_tags_to_metrics"]
api_key = "${DD_API_KEY}"