# Global config
[api]
enabled = true
address = "0.0.0.0:8686"

## Log sources
[sources.vector_agents]
type = "vector"
address = "0.0.0.0:9000"
version = "2"

[sources.datadog_agents]
type = "datadog_agent"
address = "0.0.0.0:8080"
store_api_key = false

[sources.fluent_bit_agents]
type = "fluent"
address = "0.0.0.0:24224"

[transforms.logs_router]
type = "route"
inputs = ["*_agents"]

[transforms.logs_router.route]
http_logs = 'true'
syslog_logs = 'true'
apache_common_logs = 'true'

## Remap

# Parse HTTP logs into JSON (and modify)

# Parse Syslog logs (and modify)

# Parse Apache Common logs (and modify)

## Filters

# Filter out OPTION and HEAD requests

# Filter out non-urgent logs

# Pipe everything to the console
[sinks.console_out]
type = "console"
inputs = ["*"]
target = "stdout"
encoding = { codec = "json" }

## Metrics transforms
# Limit tag cardinality

# Add tags

## BONUS

# Send to another Vector Aggregator!
