 [sources.random_syslog_logs]
type = "generator"
format = "syslog"
interval = 2

[transforms.tag]
type = "remap"
inputs = ["random_syslog_logs"]
source = '''
.tags.type = "syslog"
'''

[sinks.aggregator]
type = "vector"
inputs = ["tag"]
address = "vector_aggregator:9000"
version = "2"
healthcheck = { enabled = true }