version: '3.8'
services:
  # Vector Agents
  vector_syslog_logs_agent:
    image: timberio/vector:0.17.0-alpine
    deploy:
      replicas: 2
    volumes:
      - ./vector/agent:/etc/vector:ro
    depends_on:
      - aggregator
  # Datadog Agents
  datadog_agent:
    image: gcr.io/datadoghq/agent:7
    privileged: true
    environment:
      - DD_API_KEY
    deploy:
      replicas: 2
    volumes:
      - ./datadog:/etc/datadog-agent
      - ./logs:/tmp/logs:ro
    depends_on:
      - aggregator
  # Prometheus Node Exporters
  node_exporter:
    image: prom/node-exporter:v1.2.2
    ports:
      - 9100:9100
  # The Vector Aggregator
  aggregator:
    container_name: vector_aggregator
    image: timberio/vector:0.17.0-alpine
    ports:
      # GraphQL API for vector tap and vector top
      - 8686:8686
      # Datadog Agents
      - 8080:8080
      # Vector Agents
      - 9000:9000
    environment:
      LOG: info
    volumes:
      - ./vector/aggregator:/etc/vector:ro
  
  # Processes generating logs (ignore this)
  sensitive_user_logs:
    image: lucperkins/rando:latest
    command: [ "logs", "--kind", "sensitive", "--interval", "0.5s" ]
  
  iot_logs:
    image: lucperkins/rando:latest
    command: [ "logs", "--kind", "iot", "--interval", "0.5s" ]