[sources.random_http_logs]
type = "generator"
format = "json"
interval = 2

[transforms.tag]
type = "remap"
inputs = ["random_http_logs"]
source = '''
.tag = "http_logs"
'''

[sinks.aggregator]
type = "vector"
inputs = ["tag"]
address = "vector_aggregator:9000"
version = "2"
healthcheck = { enabled = true }