[sources.random_http_logs]
type = "generator"
format = "shuffle"
interval = 1

[transforms.tag]
type = "remap"
inputs = ["random_http_logs"]
source = '''
.tags.type = "http"
'''

[sinks.aggregator]
type = "vector"
inputs = ["tag"]
address = "vector_aggregator:9000"
version = "2"
healthcheck = { enabled = true }